### ISSUE TITLE
Hyper-param explained.

### ISSUE THREAD

**Issue by zeakey** [wy1iu/sphereface-plus#4]
Hi I got confused by part of the code:
<https://github.com/wy1iu/sphereface-plus/blob/master/tools/caffe-sfplus/src/caffe/layers/inter_class_layer.cpp#L137-L161>
```
Dtype alpha_start_iter_ = this->layer_param_.inter_class_param().alpha_start_iter();
  Dtype alpha_start_value_ = this->layer_param_.inter_class_param().alpha_start_value();
  Dtype alpha_step_ = this->layer_param_.inter_class_param().alpha_step();
  Dtype alpha_stepvalue_size = this->layer_param_.inter_class_param().alpha_stepvalue_size();
  Dtype normalize_ = this->layer_param_.inter_class_param().normalize();
  if (alpha_stepvalue_size != 0){
    const int* alpha_stepvalue_data = alpha_stepvalues.cpu_data();
    if (alpha_start_iter_ == iter_){
      alpha_ = alpha_start_value_;
    }
    else if(alpha_start_iter_ < iter_) {
      if(alpha_stepvalue_data[alpha_index_] == iter_ && alpha_index_<alpha_stepvalue_size){
        alpha_ += alpha_step_;
        alpha_index_ += (Dtype)1.;
      }
    }
  }
  else{
    if (alpha_start_iter_ == iter_){
      alpha_ = alpha_start_value_;
    }
  }
  if (top.size() == 2) {
    top[1]->mutable_cpu_data()[0] = alpha_;
  }
```

It seems that you are doing some thing like annealing, right?

Is `alpha_` the factor for energy term ($\lambda_M$ in Eq.(8) of the original paper)?

Roughly I understand that `alpha_start_iter_ ` and `alpha_start_value_` are the starting timestamp and starting value of `alpha_`.

But what does `alpha_stepvalues` mean?
Did you do something like multi-step lr scheduler that decreases `alpha_` by a factor after several iterations?

Though you left `alpha_stepvalues` empty in the configuration, I'm still curious about this part.

**Comment by zeakey** [comment]
From the code, when `iter_ < alpha_start_iter_ `, then `alpha_` keeps to be zero and the model is trained without MHE.

When `iter_` reaches `alpha_start_iter_`,  `alpha_` wakes up from `alpha_stepvalue`.

So could you mathematically describe how `alpha_` changes during training?

**Comment by liulixinkerry** [comment]
Hi @zeakey 
The value of `alpha_` remains unchanged. Thx.
