### ISSUE TITLE
do we have to train model for new faces?

### ISSUE THREAD

**Issue by robosina** [wy1iu/sphereface-plus#5]
Suppose that we have new faces to apply this method and recognize each one. In this scenario do I have to train the network on these new faces or the pretrained model will give the sufficient performance?

I ask this question because I can't get my desired accuracy , so I guess there are two possibilities 1- the pretrained model is not proper for new faces 2- I can't use caffe c++ properly.

Thank you for your great work and support.

**Comment by liulixinkerry** [comment]
Hi Leo, 
Our released model is trained by CASIA-webface. It means that the pretrained model may not be suitable for your new dataset. 
So you need to train the original sphereface network with your new face dataset first. And then you will get a model from sphereface. 
Finally, use this model as a pretrained model and train our sphereface-plus network.

**Comment by robosina** [comment]
Thanks a lot,
I will try this out.

**Comment by Maharshi-Aupera** [comment]
Hi Lixin Liu - extrapolating on what have been discussed on this thread, what do you recommend for the following questions?

1. First question:
Training the sphereface model with m = 1 on the new data-set first and then take the trained sphereface model to train sphereface-plus network with the same m = 1?
or
Training the sphereface model with m = 4 on the new data-set first and then take the trained sphereface model to train sphereface-plus network with the same m = 1?

2. Second question:
Does the chronology in training the network matter? - When I say chronology, I mean training m = 1 first then take the trained (m = 1) model to train m = 2  model and the same procedure for m = 3 and m =4 training.

**Comment by liulixinkerry** [comment]
@Maharshi-Aupera 
1. Just train the sphereface model with m=4 on the new dataset and take the trained model to train sf-plus network with m=4.
2. I think such chronology will not work, you can have a try.
