### ISSUE TITLE
maximize_inter_class_dist becomes zero when training with just one GPU instead of two

### ISSUE THREAD

**Issue by Maharshi-Aupera** [wy1iu/sphereface-plus#7]
When I run the default files (solvers and shell script) that triggers the training, it converges with two gpus. Now when i train with just one gpu, the convergence is much slower - that is understandable. 
Finally, when i train the model on just one gpu and with `iter_size=2`, that you mentioned, `maximize_inter_class_dist` in the console just becomes zero. Could you please reply on this?
Thanks.

**Comment by liulixinkerry** [comment]
Try to comment line 269 and uncomment line 273, and then rebuild the sfplus-caffe.
https://github.com/wy1iu/sphereface-plus/blob/9db39d7af175ba11612bb0d2e76fa1c553a2c468/tools/caffe-sfplus/src/caffe/layers/inter_class_layer.cu#L269

**Comment by Maharshi-Aupera** [comment]
Thanks for the prompt response.
